### ISSUE TITLE
Fixes Checklist

### ISSUE THREAD

**Issue by devdrops** [devdrops/sdk-php#1]
- [ ] PSR compliance;
- [ ] Split classes in separate files;
- [ ] Organize autoload;
- [ ] Provide better exceptions and error communication;
- [ ] Better tests;
- [ ] Code quality inspection tools;
- [ ] Do not break BC!
- [ ] Remove code samples. Use docs instead (GitHub wiki, markdown, etc) :wink:
